baseURL = "https://thephucit.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Phuc IT"
googleAnalytics = "UA-101036601-1"
disqusShortname = "ThePhucBlog"
theme = "cupper-hugo-theme"
# enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "I am looking for my slogan, my slogan will be drop here ..."
  homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer = "Copyright © 2019 The Phuc IT. All rights reserved."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4